lib/aws/xray/context.rb, lib/aws/xray/faraday.rb, spec/faraday_spec.rb
Only in Faraday middleware.
To avoid facing unexpected errors in separated environments from a web app environment. e.g. a batch environment.
=> Don't raise error when tracing has not started

README.md, lib/aws/xray.rb, lib/aws/xray/configuration.rb, lib/aws/xray/sockets.rb
We don't need tracing in development and test, so don't send tracing data using UDP socket which can be fail with `ECONNREFUSED` errono while using sendto(2) if the remote socket is absent.
=> Do not fail in development and test env

lib/aws/xray/annotation_normalizer.rb, lib/aws/xray/configuration.rb, lib/aws/xray/segment.rb, spec/annotation_normalizer_spec.rb
Becasue sending invalid annotations to xray-agent does not halt application, xray-agent just rejects that annotation or segment. So this library should not raise errors when invalid annotations are given. Just normalize them in case users forgot to pass valid data. They can notice their mistakes when they see sent annotation on X-Ray console.
=> Don't validate annotation, normalize keys and values instead

lib/aws/xray/segment.rb, spec/segment_spec.rb
Because it merges given data, not replace them.
=> Rename set_annotation and set_metadata to add_*

lib/aws/xray/request.rb, spec/segment_spec.rb
Strings from external, for example HTTP request, may contain illegal
bytes for default encoding which is UTF-8 in most cases. It can cause
encoding error while building a JSON string. To prevent that error,
ensure all strings which will be converted to a JSON string have same
encoding and do not contain any illegal bytes.
=> Fix encoding error

lib/aws/xray/error.rb, spec/error_spec.rb, spec/faraday_spec.rb
Maximum segment size is 64 kB, so we can record longer stack traces.
=> Longer stack traces

lib/aws/xray/request.rb, spec/request_spec.rb, spec/segment_spec.rb
X-Ray requires the `url` property must be "The full URL of the request, compiled from the protocol, hostname, and path of the request.". So drop query string and fragment part from given URI.
=> Drop query string and fragment part of URI

lib/aws/xray/context.rb
It can be ambitious error from AD session store:
RuntimeError (can't modify frozen String):
actionpack (4.2.7.1) lib/action_dispatch/middleware/session/abstract_store.rb:29:in `encode!'
actionpack (4.2.7.1) lib/action_dispatch/middleware/session/abstract_store.rb:29:in `generate_sid'
actionpack (4.2.7.1) lib/action_dispatch/middleware/session/cookie_store.rb:100:in `persistent_session_id!'
actionpack (4.2.7.1) lib/action_dispatch/middleware/session/cookie_store.rb:74:in `block in load_session'
actionpack (4.2.7.1) lib/action_dispatch/middleware/session/abstract_store.rb:51:in `stale_session_check!'
actionpack (4.2.7.1) lib/action_dispatch/middleware/session/cookie_store.rb:72:in `load_session'
actionpack (4.2.7.1) lib/action_dispatch/request/session.rb:180:in `load!'
actionpack (4.2.7.1) …
=> Do not freeze string from SecureRandom.hex

lib/aws/xray/context.rb, spec/context_spec.rb
With `set_current` interface, we can not guarantee the context which is
set to current thread will be removed. So change it to use-block style
method to ensure that removing.
=> Ensure set context will be removed

lib/aws/xray/hooks/net_http.rb, spec/net_http_hook_spec.rb
Due to lack of handling block argument.
follow-up PR of https://github.com/taiki45/aws-xray/pull/39.
=> HTTP#get returned nil accidentally

lib/aws/xray/client.rb, spec/client_spec.rb
Sending segments itself is not valuable operation enouth to raise errors when failed to send segments. So simply warn at `$stderr`.
=> Ignore errors on sending segments

lib/aws/xray/faraday.rb, lib/aws/xray/hooks/net_http.rb, lib/aws/xray/rack.rb, lib/aws/xray/segment.rb, spec/rack_spec.rb
Previously, aws-xray does not mark segments as errors when rack app
returens 500 response or so. These segments should be marked as errors.
=> Mark error with checking rack response

aws-xray.gemspec, lib/aws/xray/context.rb, spec/aws_xray_spec.rb, spec/rack_spec.rb, spec/spec_helper.rb
rack-timeout raises exception instead of standard error to prevent an application from catching the error: https://github.com/heroku/rack-timeout/blob/7e14d29accc0da2a2ca0400cc8bee2c277b77e12/lib/rack/timeout/core.rb#L24
=> Record rack-timeout's exception

lib/aws/xray.rb, lib/aws/xray/client.rb, lib/aws/xray/context.rb, lib/aws/xray/errors.rb, spec/client_spec.rb, spec/context_spec.rb
This library should not block application logic, so simply specify non-blocking flag to sendto(2) and if the operation which about to doing will block, just give up to send the message and pass the error to error handlers.
=> To be non-blocking

lib/aws/xray/hooks/all.rb, lib/aws/xray/hooks/net_http.rb
With this, we can simply write `require: 'aws/xray/hooks/all'` in
a Gemfile.
=> Require aws/xray in hooks

spec/configuration_spec.rb
In case aws-xray are given `AWS_XRAY_LOCATION=""` in `.env` file.
=> Test case for given double quotes

lib/aws/xray/worker.rb, spec/client_spec.rb, spec/spec_helper.rb
After fork(2) was called, all other threads except main thread are not
copied in most environments. That fork can be called by unicorn or
resque or etc. So we have to ensure our worker threads can perform jobs
after forked. To do that, clear all the workers and the queue copied
from forking process and reset them in forked process.
=> Clear queue and workers after forked

lib/aws/xray.rb, lib/aws/xray/client.rb, lib/aws/xray/context.rb, lib/aws/xray/rack.rb, lib/aws/xray/worker.rb, spec/client_spec.rb, spec/context_spec.rb, spec/faraday_spec.rb, spec/net_http_hook_spec.rb, spec/rack_spec.rb
Because now we stop sharing socket object between tracing context.
=> Stop passing Client instance

lib/aws/xray/trace.rb, spec/faraday_spec.rb, spec/net_http_hook_spec.rb, spec/rack_spec.rb, spec/segment_spec.rb, spec/subsegment_spec.rb
When trace header is missing, aws-xray generates a trace which always
has sampled value as true. To fix this bug, stop setting default value
for `sampled` argument and set proper `sampled` value with
`decide_sampling` method.
=> Fix sampling bug

README.md, lib/aws/xray.rb, lib/aws/xray/context.rb, lib/aws/xray/faraday.rb, lib/aws/xray/hooks/net_http.rb, lib/aws/xray/rack.rb, spec/aws_xray_spec.rb, spec/context_spec.rb, spec/faraday_spec.rb, spec/net_http_hook_spec.rb, spec/rack_spec.rb
`#base_trace` and `#child_trace` are not clear or intuitive name.
=> Rename tracing methods

README.md, lib/aws/xray/configuration.rb
Since this value is operational and has impact to production systems
users should not rely this default behavior. Actually we set default
value as `1` to make local development easier.
=> Change default sampling rate to undefined

lib/aws/xray/error_handlers.rb
Sometimes we have weird byte sequences for UTF-8 and it causes Aws::Xray::CanNotSendAllByteError.
=> Log strings which has an invalid byte sequence

lib/aws/xray/request.rb, spec/request_spec.rb
Don't replace to U+FFFD, but replace to empty string to avoid unexpected
behavior on send(2) in UDP socket.
Follow-up for https://github.com/taiki45/aws-xray/pull/23.
=> Remove invalid UTF-8 byte sequence

lib/aws/xray/client.rb, lib/aws/xray/worker.rb
We don't need to propagate errors which are happened in converting to
json, so doing the job in worker thread to increase performance.
=> Convert to json in worker thread

lib/aws/xray/context.rb
To enable us to search traced errors easily.
=> Add sentry tag

lib/aws/xray/context.rb, lib/aws/xray/rack.rb
Since GH #95 seems not proper, we have some sentry issues which have
"traced=1" tag but are not sampled. To deal that we add sampled context
in Rack middleware layer.
=> Record sampled or not to Sentry context

aws-xray.gemspec, lib/aws/xray/rails.rb
This PR suppresses DEPRECATION WARNING caused by [the changes on rails6](https://github.com/rails/rails/pull/34051) .
please review this 🙏 👀 @cookpad/infra 
cc/ @taiki45
=> Use Module#module_parent_name for Rails6

.travis.yml, aws-xray.gemspec, lib/aws/xray/sockets.rb
```
% RBENV_VERSION=2.6.6 bundle exec ruby -e "require 'aws/xray/sockets'"
% RBENV_VERSION=2.7.2 bundle exec ruby -e "require 'aws/xray/sockets'"
Traceback (most recent call last):
4: from -e:1:in `<main>'
3: from -e:1:in `require'
2: from /home/eagletmt/.clg/github.com/cookpad/aws-xray/lib/aws/xray/sockets.rb:1:in `<top (required)>'
1: from /home/eagletmt/.clg/github.com/cookpad/aws-xray/lib/aws/xray/sockets.rb:2:in `<module:Aws>'
/home/eagletmt/.clg/github.com/cookpad/aws-xray/lib/aws/xray/sockets.rb:12:in `<module:Xray>': uninitialized constant StringIO (NameError)
```
=> Require stringio explicitly for Ruby >= 2.7

aws-xray.gemspec, lib/aws/xray/error_handlers.rb
Support `sentry-ruby` gem in ErrorHandlerWithSentry when `sentry-ruby` gem is installed instead of `sentry-raven` gem.
@cookpad/infra Please review.
=> Support sentry-ruby gem in ErrorHandlerWithSentry
