lib/aws/xray/annotation_validator.rb, lib/aws/xray/configuration.rb, lib/aws/xray/segment.rb, spec/annotation_validator_spec.rb, spec/rack_spec.rb, spec/segment_spec.rb, spec/sub_segment_spec.rb
- Global default annotation configuration.
- Set annotation interface on segments.
=> Annotation support

README.md, lib/aws/xray/rack.rb, lib/aws/xray/rails.rb, spec/rack_spec.rb, spec/spec_helper.rb
Retry of https://github.com/taiki45/aws-xray/pull/9.
Don't automatically setup Rack middleware because sometimes users want to insert this middleware to specific position, for example, after error tracking middleware.
=> Rails integration 2

README.md, lib/aws/xray/rails.rb
This is a follow-up PR for https://github.com/taiki45/aws-xray/pull/10.
=> Use application name by default

lib/aws/xray/rack.rb
To record generated trace header to error tracker.
=> Add generated or formated trace header

lib/aws/xray/version_detector.rb, spec/version_detector_spec.rb
It may contain newline characters.
=> Chomp application version string

README.md, lib/aws/xray/rack.rb, spec/rack_spec.rb
resolve https://github.com/taiki45/aws-xray/issues/32
=> Allow users to configure excluding with regexp

lib/aws/xray/client.rb, lib/aws/xray/context.rb, lib/aws/xray/trace.rb, spec/context_spec.rb
Follow-up PR of https://github.com/taiki45/aws-xray/pull/37.
=> Don't freeze, deep copy instread

lib/aws/xray/context.rb, spec/context_spec.rb
To overwrite a name of sub segment which is recorded by net/http hook.
Because sometimes the name of these sub segments will be
indescriptive name like IP adresses.
=> Offer overwriting sub segment interface

lib/aws/xray/hooks/net_http.rb, spec/net_http_hook_spec.rb
Because it is more descriptive name.
=> Use host header value

lib/aws/xray/hooks/net_http.rb
Some library like newrelic_rpm also patch `Net::HTTP#request` and the
confliction causes stack level too deep error. To avoid that use `alias`
to prepend our patch.
=> Use alias to avoid stack level too deep error

lib/aws/xray/hooks/net_http.rb, spec/net_http_hook_spec.rb
follow-up PR for https://github.com/taiki45/aws-xray/pull/48.
=> Pass block

lib/aws/xray/client.rb, spec/client_spec.rb
Follow-up PR for https://github.com/taiki45/aws-xray/pull/56.
=> Rescue errors from error handler and log them

lib/aws/xray.rb, lib/aws/xray/client.rb, lib/aws/xray/configuration.rb, lib/aws/xray/errors.rb, lib/aws/xray/rack.rb, lib/aws/xray/worker.rb, spec/client_spec.rb, spec/context_spec.rb, spec/spec_helper.rb
Not to affect to application thread.
=> Introduce worker

aws-xray.gemspec, lib/aws/xray/request.rb, spec/net_http_hook_spec.rb, spec/schema/xray-segmentdocument-schema-v1.0.0.json, spec/segment_spec.rb, spec/spec_helper.rb
The json schema was downloaded from http://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html.
=> Use json schema to validate segments

lib/aws/xray/error_handlers.rb
https://docs.sentry.io/clients/ruby/usage/
=> Set proper error level

lib/aws/xray/segment.rb, spec/faraday_spec.rb
499 is not "too many response"...
=> Fix to use correct http status code

README.md, aws-xray.gemspec, example/fron_app_config.ru, example/recipe_app_config.ru, lib/aws/xray.rb, lib/aws/xray/faraday.rb, spec/faraday_spec.rb
resolve https://github.com/taiki45/aws-xray/issues/33
=> Drop faraday dependency

lib/aws/xray/trace.rb, spec/header_parser_spec.rb, spec/trace_spec.rb
resolve https://github.com/taiki45/aws-xray/issues/68
=> Keep custom fields in trace header

README.md, lib/aws/xray.rb, lib/aws/xray/rack.rb, lib/aws/xray/subsegment.rb, spec/aws_xray_spec.rb, spec/faraday_spec.rb, spec/net_http_hook_spec.rb, spec/rack_spec.rb
To expose most necessary methods to users. Users who want to do
something with this library should be able do all the things with these
methods.
=> Gather all necessary methods to Aws::Xray module

README.md, lib/aws/xray/caller_builder.rb, lib/aws/xray/configuration.rb, lib/aws/xray/faraday.rb, lib/aws/xray/hooks/net_http.rb, lib/aws/xray/segment.rb, spec/faraday_spec.rb, spec/net_http_hook_spec.rb, spec/spec_helper.rb
To easily find who calls this http request.
=> Record caller of http requests

lib/aws/xray/hooks/net_http.rb, spec/net_http_hook_spec.rb
When Net::HTTP instance has not been started yet, it calls
Net::HTTP#request again, and then it lets aws-xray record http requests
twice or more.
=> Don't record http request twice

lib/aws/xray/error_handlers.rb
Hi @taiki45, here's a fix for the typo I noticed in one of the error messages. 🙇‍♀️
=> Fix Segnemt -> Segment
